### ISSUE TITLE
regarding so many individual program repositories

### ISSUE THREAD

**Issue by Angryl** [Priyagarg1/c-program-17#1]
Dear @Priyagarg1,
you can put all  programs in single repository and that make your github Account look more professional, rather than putting you every single code in a separate repository. 
```this is just a suggestion ``` this is not a good practice.
Thank you

**Comment by Priyagarg1** [comment]
Respected Rudra Sir ,
                                     I will put all my programs in single
repositories according to your advice. Keep suggesting me for my mistakes .
Thank you

**Comment by Angryl** [comment]
sure, happy to help you...
